[cp]
cp1 ansible_host=
cp2 ansible_host=
cp3 ansible_host=

[workers]
w1 ansible_host=
w2 ansible_host=
w3 ansible_host=

[all:vars]
 # the username to use for the SSH connection
ansible_user=
# the path to the SSH private key file
ansible_ssh_private_key_file= 
 # the path to the Python interpreter (default is /usr/bin/python3)
ansible_python_interpreter=/usr/bin/python3
